### ISSUE TITLE
Unable to copy password on Ubuntu 16.04

### ISSUE THREAD

**Issue by Jameskmonger** [buttercup-pw/buttercup-cli#17]
The "copy password" button on Ubuntu 16.04 does nothing

**Comment by Jameskmonger** [comment]
I can confirm this is still an issue @perry-mitchell

**Comment by perry-mitchell** [comment]
Thanks James. I've abandoned all current issues as we're going to review the current architecture of the cli application.

Sorry that this wasn't clear - I'll update the readme :)

**Comment by Jameskmonger** [comment]
Ah no worries I understand @perry-mitchell. Currently I have to hack around it to `console.log` the password and then manually copy it - which obviously isn't ideal.

**Comment by perry-mitchell** [comment]
Agreed. So you've been playing with the CLI? That's cool. We need a more robust interface for terminal/server use and extracting passwords and keys is very important. 

If you come up with any ideas or suggestions for how we should make the CLI we'd love to hear it.
